"""empty message

Revision ID: 8bcdace307de
Revises: 4c7c38b2c5b0
Create Date: 2020-07-04 20:00:27.394602

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8bcdace307de'
down_revision = '4c7c38b2c5b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Show', 'start_time',
                    existing_type=sa.DATE(),
                    type_=sa.String(),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Show', 'start_time',
                    existing_type=sa.String(),
                    type_=sa.DATE(),
                    existing_nullable=False)
    # ### end Alembic commands ###
