"""empty message

Revision ID: 981e4ba10d13
Revises: bf67d9961a64
Create Date: 2020-06-22 17:42:56.509828

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '981e4ba10d13'
down_revision = 'bf67d9961a64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('website', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'website')
    # ### end Alembic commands ###
